# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Shawn D'silva
tagline: 'Developer'
description:      'Full Stack developer and Embedded Systems guy'


url:           https://shawn-dsilva.github.io
#Uncomment the below baseurl if on a local server and comment out the other baseurl
baseurl: /

#Uncomment the below baseurl if deploying to GH-Pages and comment out the other baseurl


author:
  name:           "Shawn D'silva"

paginate:         5



github:
  repo:           https://github.com/shawn-dsilva

twitter:
                  https://twitter.com/Shade978

email:  mailto:shawn.dsilva_97@protonmail.com
  
plugins_dir: [jekyll-paginate, jekyll-gist]

gems: [jekyll-paginate]
