# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Shawn D'silva
tagline:          'Tinkerer'
description:      'Embedded software developer and Tinkerer'

#baseurl: /
url:              https://shawn-dsilva.github.io/
baseurl:          /shawn-dsilva.github.io/

author:
  name:           "Shawn D'silva"

paginate:         5



github:
  repo:           https://github.com/shawn-dsilva

twitter:
                  https://twitter.com/Shade978

email:  mailto:shawn.dsilva_97@protonmail.com
  
plugins_dir: [jekyll-paginate, jekyll-gist]

gems: [jekyll-paginate]