# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Shawn D'silva
tagline: 'Programmer'
description:      'From Web Apps to Microcontroller Firmware and everything in-between'



#Uncomment the below baseurl if on a local server and comment out the other baseurl
baseurl: /

#Uncomment the below baseurl if deploying to GH-Pages and comment out the other baseurl
#baseurl:           https://shawn-dsilva.github.io/

author:
  name:           "Shawn D'silva"

paginate:         5



github:
  repo:           github.com/shawn-dsilva

twitter:
                  twitter.com/_shawndsilva

email:  shawn@shawndsilva.com

youtube: youtube.com/yourname

linkedin: linkedin.com/yourprofile
  
plugins_dir: [jekyll-paginate, jekyll-gist]

plugins: [jekyll-paginate]
