# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Shawn D'silva
tagline:          'A Jekyll theme'
description:      'embedded software developer'
#baseurl: /
baseurl:          https://github.com/shawn-dsilva/shawn-dsilva.github.io/

author:
  name:           "Shawn D'silva"

paginate:         5



github:
  repo:           https://github.com/shawn-dsilva
  
plugins: [jekyll-paginate, jekyll-gist]

